name: note_auto_route
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  floor: ^1.5.0
  sqflite: ^2.3.3+1
  auto_route: ^8.2.0
  dartz: ^0.10.1
  uuid: ^4.4.0
  intl: ^0.19.0
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  floor_generator: ^1.5.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.1.0
  
flutter:
  uses-material-design: true
